TrajectoryPlannerROS:
  max_vel_x: 0.2
  min_vel_x: 0.1 # TODO update
  max_vel_theta: 0.5
  min_in_place_vel_theta: 0.2

  acc_lim_theta: 3.0
  acc_lim_x: 2.0
  acc_lim_y: 2.0

  holonomic_robot: false # "For non-holonomic robots, no strafing velocity commands will be issued."
