local_costmap:
  # global_frame: odom
  # robot_base_frame: base_link
  # update_frequency: 5.0

  # What's the meaning of these parameters when the local costmap should never change (ie there are no dynamic obstacles)
  # publish_frequency: 5.0
  # static_map: false
  # rolling_window: true
  # width: 6.0
  # height: 6.0
  # resolution: 0.05


  # Copied from global_costmap_params:
  global_frame: map
  robot_base_frame: base_link
  update_frequency: 5.0
  # static_map: true # Implied by specified plugins
