# Position is measured from the "map" frame
# Units are meters and radians
# ALL POSITION VALUES MUST HAVE DECIMAL POINTS, IE 42.0 NOT JUST 42

tag_positions:
  standalone_tags:
    [
      {id: 0, xpos: 0.205, ypos: 0.0, zpos: 0.27, yaw: 1.571},
    ]
  tag_bundles:
    [
    ]