# Position is measured from the "map" frame
# Units are meters and radians

tag_positions:
  standalone_tags:
    [
      {id: 0, xpos: 2.0, ypos: 2.0, zpos: 1.0, yaw: 0.0},
      {id: 1, xpos: 1.5, ypos: 3.0, zpos: 1.0, yaw: 2.9},
    ]
  tag_bundles:
    [
    ]